package com.uestc.dao;

import com.uestc.domain.TbUserAccount;
import com.uestc.domain.TbUserAccountExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TbUserAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_account
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    long countByExample(TbUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_account
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    int deleteByExample(TbUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_account
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    int insert(TbUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_account
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    int insertSelective(TbUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_account
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    List<TbUserAccount> selectByExample(TbUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_account
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") TbUserAccount record, @Param("example") TbUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_account
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    int updateByExample(@Param("record") TbUserAccount record, @Param("example") TbUserAccountExample example);
}