server:
  port: 9003

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/market?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    type: org.apache.commons.dbcp.BasicDataSource
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  dubbo:
    server: true
    registry: zookeeper://47.110.255.222:2181
    protocol:
      name: dubbo
      port: 20883

mybatis:
  mapper-locations: classpath*:com/uestc/dao/*.xml
#  config-location: classpath:mybatis-config.xml


  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


