package com.uestc.dao;

import com.uestc.domain.TbStock;
import com.uestc.domain.TbStockExample;
import jdk.nashorn.internal.ir.annotations.Reference;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TbStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated Mon Jun 17 10:55:47 GMT+08:00 2019
     */
    long countByExample(TbStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated Mon Jun 17 10:55:47 GMT+08:00 2019
     */
    int deleteByExample(TbStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated Mon Jun 17 10:55:47 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated Mon Jun 17 10:55:47 GMT+08:00 2019
     */
    int insert(TbStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated Mon Jun 17 10:55:47 GMT+08:00 2019
     */
    int insertSelective(TbStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated Mon Jun 17 10:55:47 GMT+08:00 2019
     */
    List<TbStock> selectByExample(TbStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated Mon Jun 17 10:55:47 GMT+08:00 2019
     */
    TbStock selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated Mon Jun 17 10:55:47 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") TbStock record, @Param("example") TbStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated Mon Jun 17 10:55:47 GMT+08:00 2019
     */
    int updateByExample(@Param("record") TbStock record, @Param("example") TbStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated Mon Jun 17 10:55:47 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(TbStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated Mon Jun 17 10:55:47 GMT+08:00 2019
     */
    int updateByPrimaryKey(TbStock record);
}