package com.uestc.domain;

import java.math.BigDecimal;

public class TbOrderItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_item.id
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_item.goods_id
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_item.order_id
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_item.title
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_item.price
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_item.num
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_item.total_fee
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    private BigDecimal totalFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_item.pic_path
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    private String picPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_item.seller_id
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    private String sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_item.status_tcc
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    private String statusTcc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_item.message
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_item.id
     *
     * @return the value of tb_order_item.id
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_item.id
     *
     * @param id the value for tb_order_item.id
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_item.goods_id
     *
     * @return the value of tb_order_item.goods_id
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_item.goods_id
     *
     * @param goodsId the value for tb_order_item.goods_id
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_item.order_id
     *
     * @return the value of tb_order_item.order_id
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_item.order_id
     *
     * @param orderId the value for tb_order_item.order_id
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_item.title
     *
     * @return the value of tb_order_item.title
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_item.title
     *
     * @param title the value for tb_order_item.title
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_item.price
     *
     * @return the value of tb_order_item.price
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_item.price
     *
     * @param price the value for tb_order_item.price
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_item.num
     *
     * @return the value of tb_order_item.num
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_item.num
     *
     * @param num the value for tb_order_item.num
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_item.total_fee
     *
     * @return the value of tb_order_item.total_fee
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    public BigDecimal getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_item.total_fee
     *
     * @param totalFee the value for tb_order_item.total_fee
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    public void setTotalFee(BigDecimal totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_item.pic_path
     *
     * @return the value of tb_order_item.pic_path
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_item.pic_path
     *
     * @param picPath the value for tb_order_item.pic_path
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath == null ? null : picPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_item.seller_id
     *
     * @return the value of tb_order_item.seller_id
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_item.seller_id
     *
     * @param sellerId the value for tb_order_item.seller_id
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId == null ? null : sellerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_item.status_tcc
     *
     * @return the value of tb_order_item.status_tcc
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    public String getStatusTcc() {
        return statusTcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_item.status_tcc
     *
     * @param statusTcc the value for tb_order_item.status_tcc
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    public void setStatusTcc(String statusTcc) {
        this.statusTcc = statusTcc == null ? null : statusTcc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_item.message
     *
     * @return the value of tb_order_item.message
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_item.message
     *
     * @param message the value for tb_order_item.message
     *
     * @mbg.generated Mon Jun 17 13:33:00 GMT+08:00 2019
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }
}