package com.uestc.domain;

import java.math.BigDecimal;
import java.util.Date;

public class TbManagerAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager_account.id
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager_account.bank_account
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    private String bankAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager_account.account_balance
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    private BigDecimal accountBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager_account.version
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager_account.create_time
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager_account.update_time
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager_account.id
     *
     * @return the value of tb_manager_account.id
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager_account.id
     *
     * @param id the value for tb_manager_account.id
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager_account.bank_account
     *
     * @return the value of tb_manager_account.bank_account
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager_account.bank_account
     *
     * @param bankAccount the value for tb_manager_account.bank_account
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager_account.account_balance
     *
     * @return the value of tb_manager_account.account_balance
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public BigDecimal getAccountBalance() {
        return accountBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager_account.account_balance
     *
     * @param accountBalance the value for tb_manager_account.account_balance
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public void setAccountBalance(BigDecimal accountBalance) {
        this.accountBalance = accountBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager_account.version
     *
     * @return the value of tb_manager_account.version
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager_account.version
     *
     * @param version the value for tb_manager_account.version
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager_account.create_time
     *
     * @return the value of tb_manager_account.create_time
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager_account.create_time
     *
     * @param createTime the value for tb_manager_account.create_time
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager_account.update_time
     *
     * @return the value of tb_manager_account.update_time
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager_account.update_time
     *
     * @param updateTime the value for tb_manager_account.update_time
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}