package com.uestc.domain;

import java.util.Date;

public class TbStock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_stock.id
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_stock.goods_id
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_stock.seller_id
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    private String sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_stock.goods_name
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_stock.stock
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_stock.version
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_stock.creat_time
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    private Date creatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_stock.update_time
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_stock.id
     *
     * @return the value of tb_stock.id
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_stock.id
     *
     * @param id the value for tb_stock.id
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_stock.goods_id
     *
     * @return the value of tb_stock.goods_id
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_stock.goods_id
     *
     * @param goodsId the value for tb_stock.goods_id
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_stock.seller_id
     *
     * @return the value of tb_stock.seller_id
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_stock.seller_id
     *
     * @param sellerId the value for tb_stock.seller_id
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId == null ? null : sellerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_stock.goods_name
     *
     * @return the value of tb_stock.goods_name
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_stock.goods_name
     *
     * @param goodsName the value for tb_stock.goods_name
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_stock.stock
     *
     * @return the value of tb_stock.stock
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_stock.stock
     *
     * @param stock the value for tb_stock.stock
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_stock.version
     *
     * @return the value of tb_stock.version
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_stock.version
     *
     * @param version the value for tb_stock.version
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_stock.creat_time
     *
     * @return the value of tb_stock.creat_time
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_stock.creat_time
     *
     * @param creatTime the value for tb_stock.creat_time
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_stock.update_time
     *
     * @return the value of tb_stock.update_time
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_stock.update_time
     *
     * @param updateTime the value for tb_stock.update_time
     *
     * @mbg.generated Sat Jun 15 14:43:21 GMT+08:00 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}