package com.uestc.domain;

import java.util.Date;

public class TbBrokerMessagelog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_broker_messagelog.id
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_broker_messagelog.message
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_broker_messagelog.status
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_broker_messagelog.retry_count
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    private Integer retryCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_broker_messagelog.create_time
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_broker_messagelog.update_time
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_broker_messagelog.id
     *
     * @return the value of tb_broker_messagelog.id
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_broker_messagelog.id
     *
     * @param id the value for tb_broker_messagelog.id
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_broker_messagelog.message
     *
     * @return the value of tb_broker_messagelog.message
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_broker_messagelog.message
     *
     * @param message the value for tb_broker_messagelog.message
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_broker_messagelog.status
     *
     * @return the value of tb_broker_messagelog.status
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_broker_messagelog.status
     *
     * @param status the value for tb_broker_messagelog.status
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_broker_messagelog.retry_count
     *
     * @return the value of tb_broker_messagelog.retry_count
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    public Integer getRetryCount() {
        return retryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_broker_messagelog.retry_count
     *
     * @param retryCount the value for tb_broker_messagelog.retry_count
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    public void setRetryCount(Integer retryCount) {
        this.retryCount = retryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_broker_messagelog.create_time
     *
     * @return the value of tb_broker_messagelog.create_time
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_broker_messagelog.create_time
     *
     * @param createTime the value for tb_broker_messagelog.create_time
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_broker_messagelog.update_time
     *
     * @return the value of tb_broker_messagelog.update_time
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_broker_messagelog.update_time
     *
     * @param updateTime the value for tb_broker_messagelog.update_time
     *
     * @mbg.generated Sun Jun 16 11:16:25 GMT+08:00 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}