package com.uestc.dao;

import com.uestc.domain.TbManagerAccount;
import com.uestc.domain.TbManagerAccountExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TbManagerAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager_account
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    long countByExample(TbManagerAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager_account
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    int deleteByExample(TbManagerAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager_account
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager_account
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    int insert(TbManagerAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager_account
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    int insertSelective(TbManagerAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager_account
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    List<TbManagerAccount> selectByExample(TbManagerAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager_account
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    TbManagerAccount selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager_account
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") TbManagerAccount record, @Param("example") TbManagerAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager_account
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    int updateByExample(@Param("record") TbManagerAccount record, @Param("example") TbManagerAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager_account
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(TbManagerAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager_account
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    int updateByPrimaryKey(TbManagerAccount record);
}