server:
  port: 9100




spring:
  application:
    name: gateway
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/market?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    type: org.apache.commons.dbcp.BasicDataSource
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  dubbo:
    server: true
    registry: zookeeper://47.110.255.222:2181




