package com.uestc.domain;

import java.util.Date;

public class TbPackage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_package.id
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_package.seller_id
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    private String sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_package.adress
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    private String adress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_package.status
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_package.create_time
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_package.update_time
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_package.id
     *
     * @return the value of tb_package.id
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_package.id
     *
     * @param id the value for tb_package.id
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_package.seller_id
     *
     * @return the value of tb_package.seller_id
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_package.seller_id
     *
     * @param sellerId the value for tb_package.seller_id
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId == null ? null : sellerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_package.adress
     *
     * @return the value of tb_package.adress
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public String getAdress() {
        return adress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_package.adress
     *
     * @param adress the value for tb_package.adress
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public void setAdress(String adress) {
        this.adress = adress == null ? null : adress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_package.status
     *
     * @return the value of tb_package.status
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_package.status
     *
     * @param status the value for tb_package.status
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_package.create_time
     *
     * @return the value of tb_package.create_time
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_package.create_time
     *
     * @param createTime the value for tb_package.create_time
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_package.update_time
     *
     * @return the value of tb_package.update_time
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_package.update_time
     *
     * @param updateTime the value for tb_package.update_time
     *
     * @mbg.generated Sun Jun 16 15:40:20 GMT+08:00 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}